pipeline:
  name: demoRemPip1
  identifier: demoRemPip1
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testStage1
        identifier: testStage1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: stp1
                  identifier: stp1
                  spec:
                    url: <+input>
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: <+input>
                  timeout: 1d
        tags: {}
