pipeline:
  name: demoRemPip4-OIS
  identifier: demoRemPip4OIS
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: step1
                  identifier: step1
                  spec:
                    url: <+input>
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: <+input>
                  timeout: <+input>
        tags: {}
