pipeline:
  name: dummyPip
  identifier: dummyPip
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fver
        identifier: fver
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ServiceNowUpdate
                  name: erffver
                  identifier: erffver
                  spec:
                    useServiceNowTemplate: false
                    connectorRef: <+input>
                    ticketType: <+input>
                    ticketNumber: <+input>
                    fields:
                      - name: description
                        value: <+input>
                      - name: short_description
                        value: <+input>
                  timeout: 1d
          pipelineInputs: {}
        tags: {}
