pipeline:
  name: dummyPip
  identifier: dummyPip
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        template:
          templateRef: dummyStg
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: stp2
                      type: HarnessApproval
                      spec:
                        approvers:
                          minimumCount: <+input>
                      timeout: <+input>
