pipeline:
  name: git-sync-pip1
  identifier: gitsyncpip1
  projectIdentifier: GitSyncFardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: stp1
                  identifier: stp1
                  spec:
                    url: https://b.m
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: fv
                  timeout: 10s
        tags: {}
