pipeline:
  name: git-sync-p1
  identifier: gitsyncp1
  projectIdentifier: Fardeen_gitx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: stp1
                  identifier: stp1
                  spec:
                    url: <+input>
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: rwq-body
                  timeout: <+input>
        tags: {}
        variables: []
  variables:
    - name: v1
      type: String
      value: <+input>.allowedValues(67)
    - name: v2
      type: String
      value: <+input>.allowedValues(45)
    - name: v3
      type: String
      value: <+input>
