pipeline:
  name: gitSyncRem-P1
  identifier: gitSyncRemP1
  projectIdentifier: testEricGitSync
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: "stp1 "
                  identifier: stp1
                  spec:
                    url: <+input>
                    headers: []
                    outputVariables: []
                    method: <+input>
                    requestBody: erga
                  timeout: <+input>
        tags: {}
