pipeline:
  name: pip1
  identifier: pip1
  projectIdentifier: New_GitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: step1
                  identifier: step1
                  spec:
                    url: <+input>
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: <+input>
                  timeout: 9m
        tags: {}
