pipeline:
  name: piptest1
  identifier: piptest1
  projectIdentifier: Fardeen_gitx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: stp1
                  identifier: stp1
                  spec:
                    url: <+input>
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: req
                  timeout: <+input>
        tags: {}
