pipeline:
  name: rempPip
  identifier: rempPip
  projectIdentifier: defaultproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: terg
        identifier: terg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: rev
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
