pipeline:
  name: retryTest
  identifier: retryTest
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: HTTP
                  identifier: HTTP
                  spec:
                    url: <+input>
                    method: <+input>
                    headers: []
                    outputVariables: []
                    requestBody: <+input>
                  timeout: <+input>
        tags: {}
    - stage:
        name: stage2
        identifier: stage2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: HTTP
                  identifier: HTTP
                  spec:
                    url: <+input>
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: req
                  timeout: <+input>
        tags: {}
