pipeline:
  name: sourcePipRemote_PIPE-19847
  identifier: sourcePipRemote_PIPE19847
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
    - stage:
        name: stg2
        identifier: stg2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
    - stage:
        name: stg3
        identifier: stg3
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
    - stage:
        name: stgTemp
        identifier: stgTemp
        tags: {}
        template:
          templateRef: deployStgTempInsert
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              execution:
                steps:
                  - insert:
                      identifier: ins1
                      steps: <+input>
                  - stepGroup:
                      identifier: stpGrpContainerized
                      steps:
                        - step:
                            identifier: Run_1
                            type: Run
                            spec:
                              registryRef: <+input>
                              image: <+input>
                        - insert:
                            identifier: insertUnderContainerizedTemp
                            steps: <+input>
                rollbackSteps:
                  - insert:
                      identifier: insrollback
                      steps: <+input>
            variables:
              - name: er
                type: String
                value: <+input>.selectOneFrom(abc,def)
  allowStageExecutions: true
