---
pipeline:
  projectIdentifier: "Fardeen"
  orgIdentifier: "default"
  tags: {}
  stages:
  - stage:
      name: "stg"
      identifier: "stg"
      description: ""
      type: "Custom"
      spec:
        execution:
          steps:
          - step:
              type: "ShellScript"
              name: "ShellScript_1"
              identifier: "ShellScript_1"
              spec:
                shell: "Bash"
                executionTarget: {}
                source:
                  type: "Inline"
                  spec:
                    script: "exit 0"
                environmentVariables: []
                outputVariables: []
              timeout: "12m"
      tags: {}
  identifier: "sourcePipRemote_PIPE19847_Clone"
  name: "sourcePipRemote_PIPE-19847 - Clone"
