pipeline:
  name: testRawMode_RemotePip
  identifier: testRawMode_RemotePip
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
        variables:
          - name: stgVar
            type: String
            description: ""
            required: true
            value: <+input>
        strategy: <+input>
        failureStrategies: <+input>
        when: <+input>
  variables:
    - name: pipVar
      type: String
      description: ""
      required: false
      value: <+input>
