pipeline:
  name: testCDS-79260Pip
  identifier: testCDS79260Pip
  template:
    templateRef: development_pipeline
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: deployTemp
            template:
              templateInputs:
                type: Deployment
                spec:
                  service:
                    serviceRef: dockerSrvc
                    serviceInputs:
                      serviceDefinition:
                        type: Kubernetes
                        spec:
                          artifacts:
                            primary:
                              primaryArtifactRef: dockerArtifact
                              sources:
                                - identifier: dockerArtifact
                                  type: DockerRegistry
                                  spec:
                                    tag: <+input>.regex(.*-([a-f0-9]{40}))
                                    digest: <+input>
        - stage:
            identifier: approvalTemp
            template:
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: Approval_Step
                          type: HarnessApproval
                          spec:
                            approvers:
                              userGroups:
                                - account._account_all_users
                variables:
                  - name: skip_approval
                    type: String
                    value: <+input>.default(false).allowedValues(true,false)
  tags: {}
  projectIdentifier: Fardeen
  orgIdentifier: default
