pipeline:
  name: testPIE-9743
  identifier: testPIE9743
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: child
          project: naidusanity
          inputSetReferences: []
