pipeline:
  name: testRawMode_RemotePip
  identifier: testRawMode_RemotePip
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables:
                      - name: inpVar
                        type: String
                        value: <+input>
                    outputVariables: []
                  timeout: 12m
        tags: {}
        variables:
          - name: stgVar
            type: String
            description: ""
            required: true
            value: <+input>
    - stage:
        name: stg2
        identifier: stg2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
  variables:
    - name: pipVar
      type: String
      description: ""
      required: false
      value: <+input>
  allowStageExecutions: true
