pipeline:
  name: testCDS-79065
  identifier: testCDS79065
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deployStg
        identifier: deployStg
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: srv1
          environment:
            environmentRef: BrijeshEnv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: testInfra
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: approvalStg
        identifier: approvalStg
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approvalStep
                  identifier: approvalStep
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
