pipeline:
  name: testPipPIE-9743
  identifier: testPipPIE9743
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childPipPIE9743
          project: naidusanity
          inputSetReferences:
            - ino1
