pipeline:
  name: test
  identifier: test
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s
        identifier: s
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: chartmuseum
            serviceDefinition:
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: d
                      type: K8sManifest
                      spec:
                        store:
                          type: CustomRemote
                          spec:
                            filePath: d
                            extractionScript: d
                            delegateSelectors: []
                        skipResourceVersioning: false
                        valuesPaths:
                          - d
              type: Kubernetes
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          infrastructure:
            environmentRef: dummy
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: <+input>
                namespace: <+input>
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
