pipeline:
  name: testRemPip
  identifier: testRemPip
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 15m
        tags: {}
        variables:
          - name: var2
            type: String
            description: ""
            required: false
            value: "345_765"
          - name: var1
            type: String
            description: ""
            required: false
            value: "987_094"
  variables:
    - name: pipVar
      type: String
      description: ""
      required: false
      value: "1234_4321"
