pipeline:
  name: testParentFqnDiffRepo
  identifier: testParentFqnDiffRepo
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: parStg
        identifier: parStg
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childPipTempFqn
          project: Fardeen
          inputs:
            identifier: childPipTempFqn
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: stg
                      type: Custom
                      spec:
                        execution:
                          steps:
                            - step:
                                identifier: ShellScript_1
                                type: ShellScript
                                spec:
                                  source:
                                    type: Inline
                                    spec:
                                      script: <+input>
          outputs:
            - name: out1
              value: <+input>
