pipeline:
  name: testRemPip
  identifier: testRemPip
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
        variables:
          - name: var1
            type: String
            description: ""
            required: false
            value: "123_45"
          - name: var3
            type: String
            description: ""
            required: false
            value: "12_56"
  variables:
    - name: vaar6
      type: String
      description: ""
      required: false
      value: "123_321"
