pipeline:
  name: testRemPipeline123
  identifier: testRemPipeline123
  projectIdentifier: Fardeen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  when:
                    stageStatus: Failure
        tags: {}
        when:
          pipelineStatus: Failure
    - stage:
        name: stg2
        identifier: stg2
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: testRemPipeline123
          project: sunnyQA_test
          outputs: []
        tags: {}
