pipeline:
  name: testCDS-67500PreQA
  identifier: testCDS67500PreQA
  projectIdentifier: Eric
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg
        identifier: stg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
        variables:
          - name: stgVar
            type: String
            description: ""
            required: true
            value: <+input>
